schema = 1
id = "ssh-support"
label = "SSH integration dependencies"
group = "Technical dependencies"
default = true
visible = false
requirements = ["openssh", "ufw"]
tools = []
commands = ["ssh", "sshd"]
