# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = [workspace 1 silent] uwsm-app -- google-chrome-stable
exec-once = [workspace 2 silent] uwsm-app -- t3code
exec-once = [workspace 3 silent] omarchy-launch-webapp "https://youtube.com/"
exec-once = [workspace 4 silent] omarchy-launch-webapp "https://www.facebook.com/messages"
exec-once = [workspace 5 silent] uwsm-app -- steam
exec-once = [workspace 6 silent] uwsm-app -- chromium
