dofile((os.getenv("OMARCHY_PATH") or "/usr/share/omarchy") .. "/default/hypr/bootstrap.lua")
require("default.hypr.omarchy")
require("hypr.monitors")
require("hypr.input")
require("hypr.bindings")
require("hypr.looknfeel")
require("hypr.autostart")
require("default.hypr.toggles")

o.window("^google-chrome$", { workspace = "1 silent" })
o.window("^(T3 Code \\(Alpha\\)|T3 Code|t3code|t3-code-desktop)$", { workspace = "2 silent" })
o.window("^(Code|code)$", { workspace = "2 silent" })
o.window("^chrome-(www\\.)?youtube\\.com__.*$", { workspace = "3 silent" })
o.window("^(caprine|Caprine)$", { workspace = "4 silent" })
o.window("^chrome-web\\.whatsapp\\.com__.*$", { workspace = "4 silent" })
o.window("^(vesktop|Vesktop)$", { workspace = "4 silent" })
o.window("^steam$", { workspace = "5 silent" })
o.window("^chromium$", { workspace = "6 silent" })
o.window({ class = "steam", title = "Steam" }, { size = { 2200, 1100 }, center = true })
o.window("^org.omarchy.btop$", { size = { 2200, 1100 }, center = true })

hl.env("NVD_BACKEND", "direct")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("HYPRCURSOR_THEME", "Maverick Pointy Dark")
hl.env("XCURSOR_THEME", "Maverick Pointy Dark")
