schema = 2

[[bindings]]
requirement = "openssh"
provider = "repository"
package = "openssh"
repositories = ["core"]

[[bindings]]
requirement = "ufw"
provider = "repository"
package = "ufw"
repositories = ["extra"]

[[bindings]]
requirement = "chromium"
provider = "repository"
package = "chromium"
repositories = ["extra"]

[[bindings]]
requirement = "neovim"
provider = "repository"
package = "neovim"
repositories = ["extra"]

[[bindings]]
requirement = "mise"
provider = "repository"
package = "mise"
repositories = ["extra"]

[[bindings]]
requirement = "cursor-cli"
provider = "repository"
package = "cursor-cli"
repositories = ["omarchy"]

[[bindings]]
requirement = "cursor-bin"
provider = "repository"
package = "cursor-bin"
repositories = ["omarchy"]

[[bindings]]
requirement = "spotify"
provider = "repository"
package = "spotify"
repositories = ["omarchy"]

[[bindings]]
requirement = "typora"
provider = "repository"
package = "typora"
repositories = ["omarchy"]

[[bindings]]
requirement = "visual-studio-code-bin"
provider = "repository"
package = "visual-studio-code-bin"
repositories = ["omarchy"]

[[bindings]]
requirement = "steam"
provider = "repository"
package = "steam"
repositories = ["multilib"]

[[bindings]]
requirement = "lib32-mangohud"
provider = "repository"
package = "lib32-mangohud"
repositories = ["multilib"]

[[bindings]]
requirement = "filelight"
provider = "repository"
package = "filelight"
repositories = ["extra"]

[[bindings]]
requirement = "biber"
provider = "repository"
package = "biber"
repositories = ["extra"]

[[bindings]]
requirement = "texlive-basic"
provider = "repository"
package = "texlive-basic"
repositories = ["extra"]

[[bindings]]
requirement = "texlive-bibtexextra"
provider = "repository"
package = "texlive-bibtexextra"
repositories = ["extra"]

[[bindings]]
requirement = "texlive-binextra"
provider = "repository"
package = "texlive-binextra"
repositories = ["extra"]

[[bindings]]
requirement = "texlive-fontsrecommended"
provider = "repository"
package = "texlive-fontsrecommended"
repositories = ["extra"]

[[bindings]]
requirement = "texlive-latexextra"
provider = "repository"
package = "texlive-latexextra"
repositories = ["extra"]

[[bindings]]
requirement = "texlive-mathscience"
provider = "repository"
package = "texlive-mathscience"
repositories = ["extra"]

[[bindings]]
requirement = "obsidian"
provider = "repository"
package = "obsidian"
repositories = ["extra"]

[[bindings]]
requirement = "signal-desktop"
provider = "repository"
package = "signal-desktop"
repositories = ["extra"]

[[bindings]]
requirement = "nvidia-settings"
provider = "repository"
package = "nvidia-settings"
repositories = ["extra"]

[[bindings]]
requirement = "mesa-utils"
provider = "repository"
package = "mesa-utils"
repositories = ["extra"]

[[bindings]]
requirement = "vulkan-tools"
provider = "repository"
package = "vulkan-tools"
repositories = ["extra"]

[[bindings]]
requirement = "solaar"
provider = "repository"
package = "solaar"
repositories = ["extra"]

[[bindings]]
requirement = "tailscale"
provider = "repository"
package = "tailscale"
repositories = ["extra"]

[[bindings]]
requirement = "rclone"
provider = "repository"
package = "rclone"
repositories = ["extra"]

[[bindings]]
requirement = "fuse3"
provider = "repository"
package = "fuse3"
repositories = ["extra"]

[[bindings]]
requirement = "util-linux"
provider = "repository"
package = "util-linux"
repositories = ["core"]

[[bindings]]
requirement = "xmlstarlet"
provider = "repository"
package = "xmlstarlet"
repositories = ["extra"]

[[bindings]]
requirement = "yq"
provider = "repository"
package = "yq"
repositories = ["extra"]

[[bindings]]
requirement = "libqalculate"
provider = "repository"
package = "libqalculate"
repositories = ["extra"]

[[bindings]]
requirement = "rust"
provider = "repository"
package = "rust"
repositories = ["extra"]

[[bindings]]
requirement = "aws-cli-bin"
provider = "aur"
package = "aws-cli-bin"
url = "https://aur.archlinux.org/aws-cli-bin.git"
revision = "15879dbdd4f410fe7eee8c766dca24def9445da8"

[[bindings]]
requirement = "caprine"
provider = "aur"
package = "caprine"
url = "https://aur.archlinux.org/caprine.git"
revision = "5c0cea60e46ecaa489b2fbd58fdfe55709b61532"

[[bindings]]
requirement = "coolercontrol-bin"
provider = "aur"
package = "coolercontrol-bin"
url = "https://aur.archlinux.org/coolercontrol-bin.git"
revision = "c3d921dab90ff3743729060fdb60d249ffc9e7a6"

[[bindings]]
requirement = "coolercontrold-bin"
provider = "aur"
package = "coolercontrold-bin"
url = "https://aur.archlinux.org/coolercontrold-bin.git"
revision = "11a20f2153727ec531dab9c9d61e6bd03ca03b70"

[[bindings]]
requirement = "google-chrome"
provider = "aur"
package = "google-chrome"
url = "https://aur.archlinux.org/google-chrome.git"
revision = "1cf56b57305f59919b74a559906d60002edd95a3"

[[bindings]]
requirement = "losslesscut-bin"
provider = "aur"
package = "losslesscut-bin"
url = "https://aur.archlinux.org/losslesscut-bin.git"
revision = "154f094239728d8a3f65d21e506313bfae0b9267"

[[bindings]]
requirement = "t3code-nightly-bin"
provider = "aur"
package = "t3code-nightly-bin"
url = "https://aur.archlinux.org/t3code-nightly-bin.git"
revision = "c3568bb8d0b2f720fcaecc6aef94c66292f6e075"

[[bindings]]
requirement = "vesktop"
provider = "aur"
package = "vesktop"
url = "https://aur.archlinux.org/vesktop.git"
revision = "3568dd18516babd9d1256ffaa196bea72e151efd"
